[tool.ruff]

# Exclude a variety of commonly ignored directories.
exclude = [
    ".eggs",
    ".git",
    "build",
    "dist",
    "onnxscript",
]

# Same as Black.
line-length = 93

[tool.ruff.extend-per-file-ignores]
"_doc/examples/plot_*.py" = ["E402"]
"_doc/examples/plot_first_example.py" = ["F811"]
"experimental_experiment/checks.py" = ["F401"]
"experimental_experiment/torch_bench/check_model.py" = ["E402"]
"experimental_experiment/torch_bench/dort_bench.py" = ["E402"]
"experimental_experiment/torch_bench/dort_bench_profile.py" = ["E402"]
"experimental_experiment/torch_bench/dort_profile.py" = ["E402"]
"experimental_experiment/torch_bench/export_model.py" = ["E402"]
"experimental_experiment/torch_dynamo/__init__.py" = ["F401"]
"experimental_experiment/torch_interpreter/__init__.py" = ["F401"]
"experimental_experiment/xbuilder/__init__.py" = ["F401"]
"experimental_experiment/xoptim/__init__.py" = ["F401"]
