[tool.black]
line-length = 95

[tool.ruff]

# Exclude a variety of commonly ignored directories.
exclude = [
    ".eggs",
    ".git",
    "build",
    "dist",
    "onnxscript",
]

line-length = 95

[tool.ruff.lint]
# see https://docs.astral.sh/ruff/rules/
fixable = ["UP006", "UP035"]
unfixable = ["E731", "F401", "I001"]
select = [
    "B", # flake8-bugbear
    "C4", # flake8-comprehensions
    #"D", # pydocstyle
    "E", # pycodestyle
    "F", # Pyflakes
    "G", # flake8-logging-format
    #"I", # isort
    "ISC", # flake8-implicit-str-concat
    "LOG", # flake8-logging
    #"N", # pep8-naming
    #"NPY", # modern numpy
    #"PERF", # Perflint
    "PIE", # flake8-pie
    "PYI", # flake8-pyi
    "RUF", # Ruff-specific rules
    "SIM", # flake8-simplify
    "SLOT", # flake8-slot
    "T10", # flake8-debugger
    #"TID", # Disallow relative imports
    #"TRY", # flake8-try-except-raise
    "UP", # pyupgrade
    "W", # pycodestyle
    "YTT", # flake8-2020
]

[tool.ruff.lint.extend-per-file-ignores]
"**" = [
    "C401", "C408", "C413",
    "PYI041",
    "RUF010", "RUF012", "RUF100",
    "SIM102", "SIM103", "SIM108", "SIM114", "SIM910",
    "UP006", "UP015", "UP027", "UP031", "UP032", "UP034", "UP035"
]
"_doc/examples/plot_*.py" = ["E402", "B018", "PIE808", "SIM105", "SIM117"]
"_doc/notebooks/plot_*.py" = ["E402", "B018", "PIE808", "SIM105", "SIM117"]
"_doc/recipes/plot_*.py" = ["E402", "B018", "PIE808", "SIM105", "SIM117"]
"_doc/examples/plot_first_example.py" = ["F811"]
"experimental_experiment/checks.py" = ["F401"]
"experimental_experiment/torch_bench/big_models/main_spy_phi_35_vision_dummy.py" = ["E501"]
"experimental_experiment/torch_bench/check_model.py" = ["E402"]
"experimental_experiment/torch_bench/dort_bench.py" = ["E402"]
"experimental_experiment/torch_bench/dort_bench_profile.py" = ["E402"]
"experimental_experiment/torch_bench/dort_profile.py" = ["E402"]
"experimental_experiment/torch_bench/export_model.py" = ["E402"]
"experimental_experiment/torch_dynamo/__init__.py" = ["F401"]
"experimental_experiment/torch_interpreter/__init__.py" = ["F401"]
"_unittests/*/test*.py" = ["B008", "B904", "PIE808", "SIM117", "SIM105", "UP008"]
"experimental_experiment/xbuilder/__init__.py" = ["F401"]
"experimental_experiment/xoptim/__init__.py" = ["F401"]
