[tool.ruff]

# Exclude a variety of commonly ignored directories.
exclude = [
    ".eggs",
    ".git",
    "build",
    "dist",
]

# Same as Black.
line-length = 88

[tool.ruff.lint.mccabe]
# Unlike Flake8, default to a complexity level of 10.
max-complexity = 10

[tool.ruff.lint.per-file-ignores]
"_doc/examples/plot_first_example.py" = ["E402", "F811"]
"experimental_experiment/torch_dynamo/__init__.py" = ["F401"]
"experimental_experiment/torch_exp/__init__.py" = ["F401"]

