name: Check URLs

on:
  pull_request:
    branches: [main]
  schedule:
    #        ┌───────────── minute (0 - 59)
    #        │  ┌───────────── hour (0 - 23)
    #        │  │ ┌───────────── day of the month (1 - 31)
    #        │  │ │ ┌───────────── month (1 - 12 or JAN-DEC)
    #        │  │ │ │ ┌───────────── day of the week (0 - 6 or SUN-SAT)
    #        │  │ │ │ │
    #        │  │ │ │ │
    #        │  │ │ │ │
    #        *  * * * *
    - cron: '30 1 * * 0'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: urls-checker-code
      uses: urlstechie/urlchecker-action@master
      with:
        subfolder: experimental_experiment
        file_types: .md,.py,.rst,.ipynb
        print_all: false
        timeout: 2
        retry_count# : 2
        exclude_urls: https://github.com/pytorch/pytorch/pull/117009
        exclude_patterns: https://dumps.wikimedia.org/,https://github.com/pytorch/pytorch/pull/
        # force_pass : true

    - name: urls-checker-docs
      uses: urlstechie/urlchecker-action@master
      with:
        subfolder: _doc
        file_types: .md,.py,.rst,.ipynb
        print_all: false
        timeout: 2
        retry_count# : 2
        exclude_urls: https://hal.archives-,ouvertes.fr/hal-00990252/document,http://badge.fury.io/py/experimental-experiment,https://azure.microsoft.com/en-us/products/devops/pipelines,https://github.com/pytorch/pytorch/pull/83137#issuecomment-1211320670,https://github.com/NVIDIA/TransformerEngine.git@6a9edc38bf9b941b7d369af5103fa8fe0b121d61,https://medium.com/@msouza.os/llm-from-scratch-with-pytorch-9f21808c6319
        exclude_patterns: https://www.data.gouv.fr/fr/datasets/r/e3d83ab3-dc52-4c99-abaf-8a38050cc68c,https://dev.azure.com/,https://azure.microsoft.com/en-us/products/devops/pipelines,https://github.com/pytorch/pytorch/pull/83137#issuecomment-1211320670,https://github.com/NVIDIA/TransformerEngine.git@6a9edc38bf9b941b7d369af5103fa8fe0b121d61
        # force_pass : true
